name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cd-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test with Maven
        run: mvn clean install

      - name: Check deploy step (dry run)
        run: echo "Simulando deploy (dry run). Nenhum deploy será feito."
